questions = [
    {
      q_no: 1,
      q_des: "Question 1",
      res1_width: "600",
      res1_height: "225",
      res1_link: "https://i.ibb.co/b7tbF2Z/image.png",
      res1_type: "image",
      res2_present: false,
    },
    {
      q_no: 2,
      q_des: "Question 2",
      res1_width: "600",
      res1_height: "225",
      res1_link: "https://i.ibb.co/LYpZv5v/1.png",
      res1_type: "image",
      res2_present: true,
      res2_width: "170",
      res2_height: "200",
      res2_link: "https://i.ibb.co/1XzfR2M/1-1.png",
      res2_type: "image",
    },
    {
      q_no: 3,
      q_des: "Question 3",
      link: "https://i.ibb.co/M1bJBx0/3-1.png",
      res1_width: "150",
      res1_height: "280",
      res1_link: "https://i.ibb.co/4g6j58c/3-2.png",
      res1_type: "image",
      res2_present: true,
      res2_width: "180",
      res2_height: "300",
      res2_link: "https://i.ibb.co/MVSC7Nb/3-3.png",
      res2_type: "image",
    },
    {
        q_no: 4,
        q_des: "51.6, 17.2, integrate the coordinates into the price. 62442 becomes the ticket number",
        res1_width: "150",
        res1_height: "280",
        res1_link: "https://i.ibb.co/D1tgPCk/4.png",
        res1_type: "image",
        res2_present: false,
      },
  ];
  answer = ["enigma", "harbhajan singh", "ai182", "harry potter"];
  close_ans = [["enigm", "engima"], ["harbhajan", "harbhajan sing", "harbajan singh"], ["ai 182", "air india", "air india 182", "flight 182"], ["harry", "potter", "harrypotter"]];